### ISSUE TITLE
Build from source fails: `make` doesn't recognize `.mlg` extension

### ISSUE THREAD

**Issue by jaycech3n** [lukaszcz/coqhammer#13]
I'm trying to build from source, but `make` fails because it doesn't handle `hammer.mlg`.
```
[jayce@tracer coqhammer]$ make
coq_makefile -f _CoqProject -o Makefile.coq
Unknown option src/hammer.mlg
[...]
make: *** [Makefile:8: Makefile.coq] Error 1
```
I'm using the latest versions of everything. Is there a workaround?

**Comment by lukaszcz** [comment]
Use a stable release source. Probably you're not really building with the development master branch of Coq.

**Comment by jaycech3n** [comment]
Update: I get this same issue using release v1.1 of CoqHammer and a local build of Coq v8.8.
```
$ which coq_makefile
/home/jayce/bin/coq-8.8/bin/coq_makefile

$ which coqc
/home/jayce/bin/coq-8.8/bin/coqc

$ make
coq_makefile -f _CoqProject -o Makefile.coq
Unknown option src/hammer.mlg
Usage summary:
[...]
make: *** [Makefile:8: Makefile.coq] Error 1
```
I'm working with @ekiciburak on better ssreflect and mathcomp support and can install the v8.7-compatible release. It would be nice to work on the later version though. Cheers!

**Comment by lukaszcz** [comment]
You're doing something wrong. Maybe you didn't clean or didn't remove the CoqHammer files from another branch? The hammer.mlg file doesn't even exist in the release versions of CoqHammer, the src/hammer.mlg line is not present in _CoqProject.

In the development Coq master branch they changed the .ml4 files to .mlg files, with a bit different syntax. That's why the master branch of CoqHammer contains an .mlg file (because it is supposed to be compatible with Coq master branch).

**Comment by jaycech3n** [comment]
Indeed I was, cleaning and starting anew worked. Thanks very much for the explanations!
