### ISSUE TITLE
Trouble compiling 1.3.2+8.16

### ISSUE THREAD

**Issue by SnarkBoojum** [lukaszcz/coqhammer#147]
I'm having a hard time compiling the last version: I use "make" for the purpose, but since this compilation target also tries to do installation (which it shouldn't), it fails because it lacks the permission.

**Comment by SnarkBoojum** [comment]
If I try "DESTDIR=debian/tmp make", then the compilation fails because apparently at some point a compilation step needs a previous one to actually be installed and found by ocamlfind to succeed.

**Comment by lukaszcz** [comment]
"make" just does "make tactics", "make install-tactics" and then "make plugin".

The problem is that the tactics need to be installed somewhere visible for "make" for plugin compilation. I had a different build process with "make" which compiled everything without installing the tactics, but it broke after Coq PR https://github.com/coq/coq/pull/15220 and I don't know how to fix it, so I removed it.
