### ISSUE TITLE
Weird Github tar ball issues

### ISSUE THREAD

**Issue by MSoegtropIMC** [lukaszcz/coqhammer#186]
In Coq Platform the CI for 8.14 and 8.15 fails since a few days. The culprit is that these two files are no longer downloadable (404):

https://github.com/lukaszcz/coqhammer/archive/refs/tags/v1.3.2-coq8.14.tar.gz
https://github.com/lukaszcz/coqhammer/archive/refs/tags/v1.3.2-coq8.15.tar.gz

while this one works:

https://github.com/lukaszcz/coqhammer/archive/refs/tags/v1.3.2+8.19.tar.gz

As far as I can tell the paths match the tag names and also this did work for years.

Any idea what could have changed or why this is?

It dod work for years until Nov 25th and stopped working Nov 26th.

**Comment by MSoegtropIMC** [comment]
Hmm, this seems to work:

https://github.com/lukaszcz/coqhammer/archive/refs/heads/v1.3.2-coq8.14.tar.gz

@palmskog : do you have an idea what is going on here? Is the refs/tags syntax no longer valid? The refs/heads path is given by the GitHub web interface if I download the code as zip with the tag selected (and .zip replaced with .tar.gz)

**Comment by SkySkimmer** [comment]
Sounds related to https://github.blog/open-source/git/update-on-the-future-stability-of-source-code-archives-and-hashes/

**Comment by palmskog** [comment]
@MSoegtropIMC I think this is some unintentional issue with GitHub. The following link works:

https://github.com/lukaszcz/coqhammer/archive/v1.3.2-coq8.14.tar.gz

**Comment by palmskog** [comment]
Or, it may have to do with some tag/branch redundancy unique to this project? What one actually gets back is the following:
```
the given path has multiple possibilities: #<Git::Ref:0x00007f23aa606ce0>, #<Git::Ref:0x00007f23aa6057a0>
```

**Comment by palmskog** [comment]
OK, I think I found the common denominator. The `404 Not Found` is for the releases that have a dash `-` between `v1.3.2` and the Coq version, e.g., `8.14`. What is likely happening is that since there is both a branch and a tag with the same name, GitHub archiving gets confused. However, releases where the tag name and branch name are different, since there is a plus instead of a dash, work fine.

Example:

- https://github.com/lukaszcz/coqhammer/archive/refs/tags/v1.3.2+8.16.tar.gz works (has `+`)
- https://github.com/lukaszcz/coqhammer/archive/refs/tags/v1.3.2-coq8.15.tar.gz doesn't work (has `-`)

One way to work around this would be if @lukaszcz could make tags for earlier releases with `+` between version and Coq version, specifically the following tags used by the Coq Platform:
- `v1.3.2+coq8.15` (for same SHA as `v1.3.2-coq8.15`)
- `v1.3.2+coq8.14` (for same SHA as `v1.3.2-coq8.14`)

I think this has higher chance of fixing the issue quickly than talking to GitHub support.

**Comment by MSoegtropIMC** [comment]
> Or, it may have to do with some tag/branch redundancy unique to this project? What one actually gets back is the following:
> 
> ```
> the given path has multiple possibilities: #<Git::Ref:0x00007f23aa606ce0>, #<Git::Ref:0x00007f23aa6057a0>
> ```

This might indeed be. From 8.16 on (which still works) the tags and branches are named differently. But we had coq-hammer also on 8.13 and this still works. I will follow @SkySkimmer 's advice and ask GitHub. At least it is weird that it did work for 3 years or so.

**Comment by lukaszcz** [comment]
Yes, I'll do that today or this weekend.

**Comment by MSoegtropIMC** [comment]
Indeed having branches and tags with the same name seems to be problematic. If one does select the branch in the Web interface and select the tag in the web interface and then downloads the source, one gets the same url:

tag: https://github.com/lukaszcz/coqhammer/archive/refs/heads/v1.3.2-coq8.15.zip
branch: https://github.com/lukaszcz/coqhammer/archive/refs/heads/v1.3.2-coq8.15.zip

But I think that this is a bug in GitHub, that it mixes up branches and tags, so I think we should still report it. E.g. if I select the tag, I think it really selects the branch (there is a check mark on the branch afterwards in the selection list).

**Comment by palmskog** [comment]
@MSoegtropIMC please feel free to report to GitHub. However, this may take a while to be fixed, so a workaround in parallel is useful. As soon as "workaround tags" are set here, I will update the opam packages in the Coq opam archive, and hopefully then the old Platform picks will build again.

**Comment by MSoegtropIMC** [comment]
I fully agree - we should have the work around tags and change the opam files.

**Comment by lukaszcz** [comment]
I updated the tags to `+` instead of `-`. Releases for Coq 8.15 and earlier have `coq` in the tag, e.g., `v1.3.2+coq8.15` (in contrast to `v1.3.2+8.16`). As far as I can tell, the problem with downloading older releases from Github is now solved.

**Comment by lukaszcz** [comment]
Updating the tags seems to solve the issue.
