### ISSUE TITLE
Could coqhammer show counterexamples?

### ISSUE THREAD

**Issue by samuelgruetter** [lukaszcz/coqhammer#5]
I'm looking for a tool which can find counterexamples to Coq conjectures which do not hold.

For example, if I do

```
Lemma bad1: forall n, n + n + n = 2 * n.
Proof.
  hammer.
```

I just get back

```
Error: Hammer failed: ATPs failed to find a proof
```

Instead, I'd like to get something like

```
Counterexample found: 
n := 1
```

Is there an option for that? If not, would it be hard to implement? If I understand correctly, if Z3 answers `sat`, all you'd have to do would be to call `(get-model)` and either display the raw output, or, as a plus, translate it back to Coq syntax.

I think this would be a very useful feature!

**Comment by lukaszcz** [comment]
I think QuickChick does what you want (to some extent, for executable specifications at least). This is not easy to do with CoqHammer. First, the translation of the lemmas is usually inconsistent to make things more efficient, so there is no countermodel, provers fail because of timeout. This works because the provers are just not strong enough to find the inconsistency. Second, even if there is a countermodel then it's probably not very readable (because it's a countermodel for the translation) and translating it back to Coq is not necessarily trivial. Third, the translation is not complete, so even if there is a countermodel for the translated problem, the original problem may still be solvable (particularly when it uses higher-order/dependent types).

This could be done in the "hammer" way, by changing the translation to ensure consistency, (enough) completeness and easy reverse translation of the countermodels. But this is a bigger separate project.

**Comment by samuelgruetter** [comment]
Thanks for your answer, and for the pointer to Nunchaku, I hadn't seen that one before, and I'm excited to check it out!

Just to make sure I understood your answer, does the following sound correct?

CoqHammer's translation is not sound, i.e. the negation of a false conjecture is often translated into an unsatisfiable SMT problem (which would wronlgy indicate that the conjecture is true), but the unsatisfiability is so hard to find that the SMT solvers just time out, so counterexamples could only be found rarely.
Moreover, the translation is not complete either, so the negation of a true conjecture might be translated into a satisfiable SMT problem, resulting in a spurious counterexample.

**Comment by lukaszcz** [comment]
> CoqHammer's translation is not sound, i.e. the negation of a false
> conjecture is often translated into an unsatisfiable SMT problem (which
> would wronlgy indicate that the conjecture is true), but the
> unsatisfiability is so hard to find that the SMT solvers just time out, so
> counterexamples could only be found rarely.
>
Yes, mostly because you essentially get Girard's paradox in the
translation, which the provers have no chance of deriving.

> Moreover, the translation is not complete either, so the negation of a
> true conjecture might be translated into a satisfiable SMT problem,
> resulting in a spurious counterexample.
>
Yes, this is also possible, but I think much less common.

>

**Comment by samuelgruetter** [comment]
Cool, thanks again!
